'use strict';

const secp256k1 = require('secp256k1');
const { randomBytes, createHash } = require('crypto');


/**
 * A function which generates a new random Secp256k1 private key, returning
 * it as a 64 character hexadecimal string.
 *
 * Example:
 *   const privateKey = createPrivateKey();
 *   console.log(privateKey);
 *   // 'e291df3eede7f0c520fddbe5e9e53434ff7ef3c0894ed9d9cbcb6596f1cfe87e'
 */
/*
Signatures form the basis for verifiable identity and correctness on most, if not all, blockchains. 
First, a private key is generated; it's basically just a random set of bytes. 
This key is kept secret. 
Next, a cryptographic algorithm uses these bytes to derive a public key which can be widely shared. 
Finally, a signature is generated by combining the private key with some message.This signature, the message, and the public key are then all distributed together.
*/


/*
Input: a string
Output: a hash
*/

/*
  set a variable to random bytes
*/
const createPrivateKey = () => {
  //generate a private key using 32 bytes and then convert the buffer to hex
  let privKey;
  do {
    privKey = randomBytes(32);
  } while (!secp256k1.privateKeyVerify(privKey));

  return Buffer.from(privKey, 'hex').toString('hex');
};

// createPrivateKey();

/**
 * A function which takes a hexadecimal private key and returns its public pair
 * as a 66 character hexadecimal string.
 *
 * Example:
 *   const publicKey = getPublicKey(privateKey);
 *   console.log(publicKey);
 *   // '0202694593ddc71061e622222ed400f5373cfa7ea607ce106cca3f039b0f9a0123'
 *
 * Hint:
 *   Remember that the secp256k1-node library expects raw bytes (i.e Buffers),
 *   not hex strings! You'll have to convert the private key.
 */
const getPublicKey = privateKey => {
  //convert the private key to a hex and then return the public key as a hex string
  const bPrivKey = Buffer.from(privateKey, 'hex');
  const pubKey = secp256k1.publicKeyCreate(bPrivKey);
  
  return pubKey.toString('hex');
};


/**
 * A function which takes a hex private key and a string message, returning
 * a 128 character hexadecimal signature.
 *
 * Example:
 *   const signature = sign(privateKey, 'Hello World!');
 *   console.log(signature);
 *   // '4ae1f0b20382ad628804a5a66e09cc6bdf2c83fa64f8017e98d84cc75a1a71b52...'
 *
 * Hint:
 *   Remember that you need to sign a SHA-256 hash of the message,
 *   not the message itself!
 */
const sign = (privateKey, message) => {
  const bPrivate = Buffer.from(privateKey, 'hex');
  const hash = createHash('sha256');
  hash.update(message);
  const bMessage = Buffer.from(hash.digest('hex'), 'hex');
  const sigObj = secp256k1.sign(bMessage, bPrivate);

  return sigObj['signature'].toString('hex');
};


/**
 * A function which takes a hex public key, a string message, and a hex
 * signature, and returns either true or false.
 *
 * Example:
 *   console.log( verify(publicKey, 'Hello World!', signature) );
 *   // true
 *   console.log( verify(publicKey, 'Hello World?', signature) );
 *   // false
 */
const verify = (publicKey, message, signature) => {
  const pKey = Buffer.from(publicKey, 'hex');
  const hash = createHash('sha256');
  hash.update(message);
  const pMessage = Buffer.from(hash.digest('hex'), 'hex');
  const pSig = Buffer.from(signature, 'hex');
  const verObj = secp256k1.verify(pMessage, pSig, pKey);

  return verObj;
};

module.exports = {
  createPrivateKey,
  getPublicKey,
  sign,
  verify
};
